### PR TITLE
add length property

### PR DESCRIPTION
**Pull request by antonmes**
linked to https://github.com/Zewo/libvenice/pull/5

### CODE REVIEW

**Comment by Danappelxx** [comment]
LGMT - @paulofaria can I merge?

Edit: realized that this pr should be merged alongside zewo/libvenice#5

**Comment by antonmes** [comment]
yeah, i had to mention it. fixed.

**Comment by paulofaria** [comment]
`fileeof` follows the same semantics as `feof` in the sense that it only returns false when you try to read from a fd and it returns 0. this would change this semantics right? we can change the semantics, but this has to be clear from the docs (non-existent, yeah, this is a problem).

fwict the semantics of `feof` would only apply to non regular files, is that it?

**Comment by antonmes** [comment]
hah, i was confused by libmill tests, so that version of eof is incorrect.. we should fix libmill then :)
fixed.

**Comment by antonmes** [comment]
Moved here https://github.com/VeniceX/File/pull/4

**Pull request closed without merging**
